export default dummy_data = [
  {
    id: 1,
    awayTeam: "CS Dinamo Bucureşti",
    homeTeam: "BC CSU Sibiu",
    awayTeamScore: "67",
    homeTeamScore: "84",
    referee: "Ciulin Marius",
    arena: "Arena de Baschet ",
    matchDate: new Date("2023-03-10"),
    matchTime: "18:00",
    awayTeamLogo:
      "https://www.baschet.ro/storage/10884/conversions/dinamosigla-thumb.jpg",
    homeTeamLogo:
      "https://www.baschet.ro/storage/84/conversions/CSU_Sibiu_logo-thumb.jpg",
    awayTeamStats: [
      {
        playerName: "Sasha Son",
        playerNumber: "7",
        minutesPlayed: "DNP",
        two_fgm: "-",
        two_fga: "-",
        two_fgp: "-",
        three_fgm: "-",
        three_fga: "-",
        three_fgp: "-",
        ftm: "-",
        fta: "-",
        ftp: "-",
        reb: "-",
        ass: "-",
        fouls: "-",
        tov: "-",
        blocks: "-",
        pts: "-",
      },
      {
        playerName: "Darnell Edge",
        playerNumber: "1",
        minutesPlayed: "28:54",
        two_fgm: "3",
        two_fga: "5",
        two_fgp: "60.0",
        three_fgm: "0",
        three_fga: "3",
        three_fgp: "0.0",
        ftm: "0",
        fta: "1",
        ftp: "0.0",
        reb: "3",
        ass: "1",
        fouls: "1",
        tov: "2",
        blocks: "0",
        pts: "6",
      },
      {
        playerName: "Donte Ingram",
        playerNumber: "2",
        minutesPlayed: "38:16",
        two_fgm: "1",
        two_fga: "2",
        two_fgp: "50.0",
        three_fgm: "2",
        three_fga: "3",
        three_fgp: "66.0",
        ftm: "4",
        fta: "4",
        ftp: "100.0",
        reb: "6",
        ass: "3",
        fouls: "1",
        tov: "3",
        blocks: "0",
        pts: "12",
      },
      {
        playerName: "Andrei Mandache",
        playerNumber: "4",
        minutesPlayed: "37:13",
        two_fgm: "4",
        two_fga: "8",
        two_fgp: "50.0",
        three_fgm: "0",
        three_fga: "3",
        three_fgp: "0.0",
        ftm: "2",
        fta: "2",
        ftp: "100.0",
        reb: "2",
        ass: "4",
        fouls: "3",
        tov: "1",
        blocks: "0",
        pts: "10",
      },
      {
        playerName: "David Andrei Patru",
        playerNumber: "8",
        minutesPlayed: "04:11",
        two_fgm: "0",
        two_fga: "0",
        two_fgp: "0.0",
        three_fgm: "0",
        three_fga: "1",
        three_fgp: "0.0",
        ftm: "0",
        fta: "0",
        ftp: "0.0",
        reb: "0",
        ass: "0",
        fouls: "0",
        tov: "0",
        blocks: "0",
        pts: "0",
      },
      {
        playerName: "Stefan Grasu",
        playerNumber: "11",
        minutesPlayed: "25:37",
        two_fgm: "4",
        two_fga: "4",
        two_fgp: "100.0",
        three_fgm: "1",
        three_fga: "1",
        three_fgp: "100.0",
        ftm: "2",
        fta: "4",
        ftp: "50.0",
        reb: "1",
        ass: "1",
        fouls: "5",
        tov: "1",
        blocks: "1",
        pts: "13",
      },
      {
        playerName: "Jakub Wojciechowski",
        playerNumber: "23",
        minutesPlayed: "22:31",
        two_fgm: "1",
        two_fga: "2",
        two_fgp: "50.0",
        three_fgm: "2",
        three_fga: "6",
        three_fgp: "33.0",
        ftm: "1",
        fta: "2",
        ftp: "50.0",
        reb: "5",
        ass: "2",
        fouls: "1",
        tov: "2",
        blocks: "1",
        pts: "9",
      },
      {
        playerName: "Radu Vîrnă",
        playerNumber: "22",
        minutesPlayed: "DNP",
        two_fgm: "-",
        two_fga: "-",
        two_fgp: "-",
        three_fgm: "-",
        three_fga: "-",
        three_fgp: "-",
        ftm: "-",
        fta: "-",
        ftp: "-",
        reb: "-",
        ass: "-",
        fouls: "-",
        tov: "-",
        blocks: "-",
        pts: "-",
      },
      {
        playerName: "Malcolm Griffin",
        playerNumber: "25",
        minutesPlayed: "17:36",
        two_fgm: "2",
        two_fga: "2",
        two_fgp: "100.0",
        three_fgm: "0",
        three_fga: "5",
        three_fgp: "0.0",
        ftm: "0",
        fta: "0",
        ftp: "0.0",
        reb: "1",
        ass: "3",
        fouls: "5",
        tov: "1",
        blocks: "0",
        pts: "4",
      },
      {
        playerName: "Alexandru Moroșanu",
        playerNumber: "30",
        minutesPlayed: "DNP",
        two_fgm: "-",
        two_fga: "-",
        two_fgp: "-",
        three_fgm: "-",
        three_fga: "-",
        three_fgp: "-",
        ftm: "-",
        fta: "-",
        ftp: "-",
        reb: "-",
        ass: "-",
        fouls: "-",
        tov: "-",
        blocks: "-",
        pts: "-",
      },
      {
        playerName: "Andy  Ogide",
        playerNumber: "24",
        minutesPlayed: "25:42",
        two_fgm: "4",
        two_fga: "7",
        two_fgp: "57.0",
        three_fgm: "1",
        three_fga: "5",
        three_fgp: "20.0",
        ftm: "2",
        fta: "3",
        ftp: "66.0",
        reb: "3",
        ass: "2",
        fouls: "0",
        tov: "1",
        blocks: "0",
        pts: "13",
      },
      {
        playerName: "Marquis Addison",
        playerNumber: "34",
        minutesPlayed: "DNP",
        two_fgm: "-",
        two_fga: "-",
        two_fgp: "-",
        three_fgm: "-",
        three_fga: "-",
        three_fgp: "-",
        ftm: "-",
        fta: "-",
        ftp: "-",
        reb: "-",
        ass: "-",
        fouls: "-",
        tov: "-",
        blocks: "-",
        pts: "-",
      },
    ],
    homeTeamsStats: [
      {
        playerName: "Monyea Pratt",
        playerNumber: "1",
        minutesPlayed: "29:54",
        two_fgm: "1",
        two_fga: "4",
        two_fgp: "25.0",
        three_fgm: "2",
        three_fga: "2",
        three_fgp: "100.0",
        ftm: "0",
        fta: "0",
        ftp: "0.0",
        reb: "11",
        ass: "8",
        fouls: "2",
        tov: "1",
        blocks: "0",
        pts: "8",
      },
      {
        playerName: "Gaston Whelan",
        playerNumber: "2",
        minutesPlayed: "29:34",
        two_fgm: "6",
        two_fga: "9",
        two_fgp: "66.0",
        three_fgm: "2",
        three_fga: "5",
        three_fgp: "40.0",
        ftm: "2",
        fta: "4",
        ftp: "50.0",
        reb: "1",
        ass: "4",
        fouls: "3",
        tov: "5",
        blocks: "0",
        pts: "20",
      },
      {
        playerName: "Bogdan Bădițăscu",
        playerNumber: "5",
        minutesPlayed: "DNP",
        two_fgm: "-",
        two_fga: "-",
        two_fgp: "-",
        three_fgm: "-",
        three_fga: "-",
        three_fgp: "-",
        ftm: "-",
        fta: "-",
        ftp: "-",
        reb: "-",
        ass: "-",
        fouls: "-",
        tov: "-",
        blocks: "-",
        pts: "-",
      },
      {
        playerName: "Roberts Blumbergs",
        playerNumber: "6",
        minutesPlayed: "29:47",
        two_fgm: "2",
        two_fga: "4",
        two_fgp: "50.0",
        three_fgm: "3",
        three_fga: "7",
        three_fgp: "42.0",
        ftm: "1",
        fta: "2",
        ftp: "50.0",
        reb: "5",
        ass: "4",
        fouls: "2",
        tov: "1",
        blocks: "0",
        pts: "14",
      },
      {
        playerName: "Mirel Dragoste",
        playerNumber: "7",
        minutesPlayed: "30:25",
        two_fgm: "1",
        two_fga: "1",
        two_fgp: "100.0",
        three_fgm: "2",
        three_fga: "5",
        three_fgp: "40.0",
        ftm: "0",
        fta: "2",
        ftp: "0.0",
        reb: "6",
        ass: "1",
        fouls: "1",
        tov: "1",
        blocks: "0",
        pts: "8",
      },
      {
        playerName: "Aurelian Gavriloaia",
        playerNumber: "8",
        minutesPlayed: "11:48",
        two_fgm: "0",
        two_fga: "1",
        two_fgp: "0.0",
        three_fgm: "1",
        three_fga: "3",
        three_fgp: "33.0",
        ftm: "0",
        fta: "0",
        ftp: "0.0",
        reb: "0",
        ass: "0",
        fouls: "1",
        tov: "1",
        blocks: "0",
        pts: "3",
      },
      {
        playerName: "Paolo Marinelli",
        playerNumber: "10",
        minutesPlayed: "11:44",
        two_fgm: "1",
        two_fga: "1",
        two_fgp: "100.0",
        three_fgm: "1",
        three_fga: "2",
        three_fgp: "50.0",
        ftm: "2",
        fta: "2",
        ftp: "100.0",
        reb: "1",
        ass: "4",
        fouls: "3",
        tov: "1",
        blocks: "0",
        pts: "7",
      },
      {
        playerName: "Daniel Manchon",
        playerNumber: "11",
        minutesPlayed: "10:52",
        two_fgm: "2",
        two_fga: "2",
        two_fgp: "100.0",
        three_fgm: "2",
        three_fga: "4",
        three_fgp: "50.0",
        ftm: "0",
        fta: "0",
        ftp: "0.0",
        reb: "2",
        ass: "2",
        fouls: "1",
        tov: "2",
        blocks: "0",
        pts: "10",
      },
      {
        playerName: "Mouhamed Barro",
        playerNumber: "24",
        minutesPlayed: "11:32",
        two_fgm: "3",
        two_fga: "3",
        two_fgp: "100.0",
        three_fgm: "0",
        three_fga: "0",
        three_fgp: "0.0",
        ftm: "0",
        fta: "0",
        ftp: "0.0",
        reb: "4",
        ass: "1",
        fouls: "3",
        tov: "1",
        blocks: "0",
        pts: "6",
      },
      {
        playerName: "Sebastian Ionescu",
        playerNumber: "31",
        minutesPlayed: "03:29",
        two_fgm: "0",
        two_fga: "0",
        two_fgp: "0.0",
        three_fgm: "0",
        three_fga: "0",
        three_fgp: "0.0",
        ftm: "0",
        fta: "0",
        ftp: "0.0",
        reb: "0",
        ass: "0",
        fouls: "0",
        tov: "1",
        blocks: "0",
        pts: "0",
      },
      {
        playerName: "Daniel Banciu",
        playerNumber: "42",
        minutesPlayed: "DNP",
        two_fgm: "-",
        two_fga: "-",
        two_fgp: "-",
        three_fgm: "-",
        three_fga: "-",
        three_fgp: "-",
        ftm: "-",
        fta: "-",
        ftp: "-",
        reb: "-",
        ass: "-",
        fouls: "-",
        tov: "-",
        blocks: "-",
        pts: "-",
      },
      {
        playerName: "Rareș Uță",
        playerNumber: "44",
        minutesPlayed: "28:28",
        two_fgm: "3",
        two_fga: "7",
        two_fgp: "42.0",
        three_fgm: "0",
        three_fga: "0",
        three_fgp: "0.0",
        ftm: "2",
        fta: "2",
        ftp: "100.0",
        reb: "6",
        ass: "1",
        fouls: "1",
        tov: "4",
        blocks: "2",
        pts: "8",
      },
    ],
  },
];
